### ISSUE TITLE
Bug: Missing SQL table

### ISSUE THREAD

**Issue by Tiimon** [project-error/new-phone-who-dis#103]
**Is this issue related to the phone still being in development?**
If so, please consult the [gitkraken](https://app.gitkraken.com/glo/board/X9YZ_x_SVQEcMwpH) to see if it's already being tracked. 

**Describe the bug**
The npwd_bank_transfers table is missing in the import.sql

**To Reproduce**
1. Load into the server and open phone

**Expected behavior**
Table should exist

**Evidence**
When opening the phone you're met with this error in the server side console `[NPWD] [bank] [error]: Failed to fetch transactions, Table 'es_extended.npwd_bank_transfers' doesn't exist`. After looking into the import.sql file provided there is no statement that creates this table

**Needed information (please complete the following information):**
 - **Server OS**: Windows 10 Server
- **Server Artifact version**: 3534
- What version of **new-phone-who-dis** are you running?: Newest fork

**Additional context**
N/A

**Comment by itschip** [comment]
This is not implemented yet, as we don't know if we are going to to use a third part resource to handle transactions, or not. 

This is an known "issue", and will be resolved as soon as we figure something out. If you have any suggestions, feel free to share them.

**Comment by RockySouthpaw** [comment]
Will add this to gitkraken shortly. Thank you for opening this issue.

**Comment by itschip** [comment]
Closing this for now, as we are probably not releasing the phone with transfers and the bank resource. You can open this when said resource is released, if you wish to do such.
