### ISSUE TITLE
Enhancement: Allow for Config to be edited without rebuild

### ISSUE THREAD

**Issue by TasoOneAsia** [project-error/new-phone-who-dis#206]
**Is your feature request related to a problem or design oversight? If so, please explain it.**
Design oversight

**What is your suggestion?**
To allow for the config to be edited only requiring a resource restart & not a total rebuild of the phone

**Any additional comments or concerns?**

This can be done by either using a dynamic `require`, which imports the `config.json` at runtime or by using the native `LoadResourceFile` to also dynamically load at runtime.

**Comment by RockySouthpaw** [comment]
Sg2m, this was an initial concern pre release on how to handle the config for various things as building the phone isn’t something some of the newer server owners will understand despite the docs being well wrote.

**Comment by TasoOneAsia** [comment]
Closed by #207
