### ISSUE TITLE
Enhancement: Add data validation to restrict field length when adding contacts to avoid errors.

### ISSUE THREAD

**Issue by RockySouthpaw** [project-error/new-phone-who-dis#223]
**Is your feature request related to a problem or design oversight? If so, please explain it.**
Yes

**What is your suggestion?**
Restrict the name and number field when adding a new contact to 60/10 characters respectively as this is the current length for the SQL.

**Any additional comments or concerns?**
Currently this results in errors within the server console as such:
![image](https://user-images.githubusercontent.com/55056068/117560417-86804d80-b05b-11eb-991a-debc4ec1a780.png)
![image](https://user-images.githubusercontent.com/55056068/117560455-e119a980-b05b-11eb-93a2-70be4751a971.png)

It's not really "breaking" as the phone behaves correctly, it just makes sense to avoid the issue all together.

**Comment by RockySouthpaw** [comment]
Should also add data validation to the number field as this currently allows you to input letters.

**Comment by RockySouthpaw** [comment]
This also exist within the Dialer as there is no data validation for if what you’re typing is a number or the length.

**Comment by itschip** [comment]
I'll look at the issue now wii

**Comment by itschip** [comment]
Fixed.

**Comment by RockySouthpaw** [comment]
https://github.com/project-error/new-phone-who-dis/commit/c5aaf32e5d1a4852df9777f9d1b0c801e7b85d3b the length was increased from 60 to 255. If someone does 256 then It’ll occur again but whatever 🤷🏻‍♀️ This will probably never occur unless someone is being weird.
