### ISSUE TITLE
npwd:newPlayer / unloadPlayer

### ISSUE THREAD

**Issue by benzon** [project-error/new-phone-who-dis#226]
**Is this issue related to the phone still being in development?**
![16211156110d8f8ddef248a4fe6df39192fbf427fa](https://user-images.githubusercontent.com/3528000/118379240-20567600-b5d9-11eb-8ccb-fd7dde61f0cc.jpg)

**Describe the bug**
Trying to add player data via event, since the char system im working on, is not using regular identifiers

tryed TriggerEvent('npwd:newPlayer', {playerId, identifier, firstname, lastname}) and TriggerEvent('npwd:newPlayer', tonumber(playerId), identifier, firstname, lastname)

The screenshot shows none of the values are nil and contains data, but it refuses to work in any way or form

**To Reproduce**
Trying to send data via trigger for newPlayer event

**Comment by RockySouthpaw** [comment]
Can you show the code you added to your resource

**Comment by benzon** [comment]
Figured it out :)

Format should be
TriggerEvent('npwd:newPlayer', {source = playerId, identifier = identifier, firstname = firstname, lastname = lastname})
