### ISSUE TITLE
Twitter freeze the game

### ISSUE THREAD

**Issue by Own-plf** [project-error/new-phone-who-dis#229]
when i clic on twitter icon, i must restart the script.
I can re-open phone, close etc etc but no image
https://gyazo.com/c456acaca43e8c83c079d8cdaf446048

**Comment by itschip** [comment]
Do you have the newest SQL structure installed? If not, delete all the npwd tables, and install it agian. If you have, empty all the tables.

**Comment by RockySouthpaw** [comment]
Can you also edit this post to be in line with the GitHub issue template?

**Comment by AvarianKnight** [comment]
@itschip was this possibly fixed with latest commits?

**Comment by itschip** [comment]
> @itschip was this possibly fixed with latest commits?

@AvarianKnight Could be fixed, not sure until it occurs again, if it ever will.

**Comment by RockySouthpaw** [comment]
@Own-plf can you please retest to see if this issue still exist?

**Comment by Own-plf** [comment]
I ll retry asap, i come back to you soon

**Comment by RockySouthpaw** [comment]
Couldn't reproduce the issue again as i think this resolved. If you encounter the issue again please reach out to us on the Discord :)
