### ISSUE TITLE
Enhancement: Mobilepay/Applepay/GooglePay

### ISSUE THREAD

**Issue by benzon** [project-error/new-phone-who-dis#237]
Not sure if the bank app can do this, but it could be a part of it.

Here in Denmark where im from we got something called MobilePay, it's an app where we can transfer money to friends, companys and what not, even request a payment.

A simple version of this could be nice, where you transfer based on phone number.

Found a video https://www.youtube.com/watch?v=Z6ho7u0sei4 - it's very danish but it showcases the idea.

**Comment by RockySouthpaw** [comment]
There’s a bank app that is WIP. It would allow you to transfer money to another player as you described. It’s just not a priority right now so it’s not part of our road to release work flow.

**Comment by benzon** [comment]
Uhm okay i think it should be a part since it's a core function the bank part, and it would make life easyer on everyone i do think.

**Comment by RockySouthpaw** [comment]
So i discussed it with @itschip and this is already a planned feature to allow transfers with phone numbers / contacts. Closing this as a result. :) Thank you for taking the time to suggest this. The bank app is still super WIP so if you have any more bank related suggestions please use the Discord. ❤️
