### ISSUE TITLE
GCPHONE

### ISSUE THREAD

**Issue by vpayso** [project-error/new-phone-who-dis#46]
Do I need ignited to install this or this by itself is okay?

**Comment by TasoOneAsia** [comment]
You dont install this in general unless you are a developer looking to contribute. This phone is not yet complete.

**Comment by XiosBombay** [comment]
This is not ready for public use. You can however PR the phone (not currently looking for functionality, just translations).

**Comment by vpayso** [comment]
Basically im trying to run on a vmenu server. Ive seen it done. numbers generate and all. Idk how to work it.

**Comment by XiosBombay** [comment]
> Basically im trying to run on a vmenu server. Ive seen it done. numbers generate and all. Idk how to work it.

It's not supposed to be used yet.
