### ISSUE TITLE
Bug: Camera does not change back to rear facing mode using up arrow

### ISSUE THREAD

**Issue by Tiimon** [project-error/new-phone-who-dis#98]
**Describe the bug**
When the user tries to switch between rear facing and front facing on the camera the phone just does an animation but stays on front facing mode

**To Reproduce**
1. Open Phone
2. Click Camera
3. Click Add
4. Press up arrow (it should go to selfie mode)
5. Click up arrow again and it does not go back to rear facing mode

**Expected behavior**
It should transition between front facing and rear facing camera on up arrow press

**Evidence**
https://gyazo.com/c2eb35a25daed00ad9234146730a03a9

**Needed information (please complete the following information):**
 - **Server OS**: Windows 10 Server
- **Server Artifact version**: 3502
- What version of **new-phone-who-dis** are you running?: Version as of 2 hours ago on GitHub

**Additional context**
N/A

**Comment by RockySouthpaw** [comment]
It’s unfinished. Not an issue.

**Comment by RockySouthpaw** [comment]
You’ll also notice some more bugs with the camera app if you continue to play around with it. Can see them [here](https://app.gitkraken.com/glo/view/card/45fa90430f1c499b8ad143d33507936b)

**Comment by itschip** [comment]
@Tiimon Thanks for submitting the issue. This will be fixed shortly 👍
